### ISSUE TITLE
Event Endpoint for Console Not Working

### ISSUE THREAD

**Issue by DeveloperPaul123** [LartTyler/MHWDB-API#111]
Currently the [event](https://mhw-db.com/events) endpoint is not pulling any data for consoles. Could be due to change in structure for that page with the addition of master rank?

**Comment by LartTyler** [comment]
It seems odd that adding a button to the top of the page would change their markup enough to break the scraper, but it's possible. Hopefully it'll be an easy fix, thanks for letting me know!

**Comment by LartTyler** [comment]
This should be resolved with [v1.16.1](https://github.com/LartTyler/MHWDB-API/releases/tag/1.16.1). Looks like they fixed a typo in the `for` attribute of the timezone selector, which the scraper needed in order to determine timezone offsets. Since it couldn't determine the timezone, it couldn't scrape any of the data for console.

**Comment by DeveloperPaul123** [comment]
Yeah I saw your PR, glad it was an easy fix! Thanks for the prompt response.
