### ISSUE TITLE
Add true attack values in the weapon resource

### ISSUE THREAD

**Issue by stocky37** [LartTyler/MHWDB-API#55]
The muted value next to the displayed attack value is the true attack value with the display modifier taken into account. This would save consumers from having to store display modifier values and calculate true raws themselves.

**Comment by LartTyler** [comment]
I'm not sure what you're referring to, sorry. Are you talking about something on a site like Kiranico? The only thing I can think of is the value on the right side of the pipe in the "Attack" field on the weapon pages on Kiranico (i.e. [here](https://mhworld.kiranico.com/weapon/iron-katana-i)). Is that what you mean?

**Comment by LartTyler** [comment]
No worries! I just wanted to double check that I assumed correctly. If it were up to you, how would you like to see that value represented? I already have plans to move `attributes.attack` up to the top level of the object (similar to what I recently did with `attributes.defense` on armor). I could do that and your requested change at the same time, yielding something like this.

```json
{
  "attack": {
    "value": 384,
    "raw": 80
  }
}
```

So, instead of pulling attack from `weapon.attributes.attack`, you could get the attack value as it exists now from `weapon.attack.value` and the true value you mentioned in your original post from `weapon.attack.raw`.

**Comment by stocky37** [comment]
I like it. The only thing I would maybe change would be to change the value property to something a little more descriptive. Maybe something like this:
```json
{
  "attack": {
    "display": 384,
    "raw": 80
  }
}
```

As it stands the design is already perfectly useable so completely up to you.

**Comment by LartTyler** [comment]
Calling it `display` works for me. I'll try to get that into the next release!

**Comment by LartTyler** [comment]
This has been added with the release of [v1.11.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.11.0).
